### ISSUE TITLE
Não existe section 

### ISSUE THREAD

**Issue by bernardojeronimo** [rodrigomacsantos/rodrigomacsantos.github.io#5]
https://github.com/rodrigomacsantos/rodrigomacsantos.github.io/blob/7f585ff9c0f24f3713bba3973ddee2d1dc469543/lab3/multimedia.html#L24
https://github.com/rodrigomacsantos/rodrigomacsantos.github.io/blob/7f585ff9c0f24f3713bba3973ddee2d1dc469543/lab3/multimedia.html#L30
https://github.com/rodrigomacsantos/rodrigomacsantos.github.io/blob/7f585ff9c0f24f3713bba3973ddee2d1dc469543/lab3/multimedia.html#L32

Usar section para agrupar argumentos do mesmo tipo. Definir uma section para as fotografias, uma para o video e outra para o poema

**Comment by rodrigomacsantos** [comment]
adicionei as sections
